[package]
name = "mpv-mpris2"
version = "0.0.1-alpha5"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/plugin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.4.0"
scopeguard = "1.2.0"
serde_json = "1.0.105"
smol = "1.3.0"
url = "2.4.0"
zbus = "3.14.1"

[build-dependencies]
bindgen = "0.66.1"
