[package]
name = "mpv-mpris2"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/plugin.rs"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
_unused1 = { version = "=1.7", package = "async-process" } # prevent duplicate event-listener
_unused2 = { version = "=0.2.4", package = "async-signal" } # prevent duplicate async-io
anyhow = "1"
data-encoding = "2"
scopeguard = "1"
serde_json = "1"
smol = "1"
url = "2"
zbus = "3"

[build-dependencies]
bindgen = "0.69"
pkg-config = "0.3"
