[workspace]
members = ["cargo:."]

[dist]
dist = true
cargo-dist-version = "0.32.0"
packages = ["mpris"]
targets = ["x86_64-unknown-linux-gnu"]
cargo-auditable = true
unix-archive = ".tar.zst"
ci = "github"

[dist.dependencies.apt]
mpv = "*"
