name: Rust

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libmpv-dev
      - run: rustup default stable
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install required clippy tools
        run: cargo install clippy-sarif sarif-fmt
      - name: Run rust-clippy
        run: |
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
      - run: |
          cargo build --release --locked --target x86_64-unknown-linux-gnu
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          cp target/x86_64-unknown-linux-gnu/release/libmpv_mpris2.so mpris-x86_64-unknown-linux-gnu.so
          strip --strip-unneeded mpris-x86_64-unknown-linux-gnu.so
      - if: startsWith(github.ref, 'refs/tags/')
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: mpris-x86_64-unknown-linux-gnu.so
