name: Rust

on:
  push:
    branches-ignore:
      - "dependabot/**"
      - "pr/**"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libmpv-dev
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          cargo build --release --locked --target x86_64-unknown-linux-gnu
      - if: startsWith(github.ref, 'refs/tags/v')
        run: cp target/x86_64-unknown-linux-gnu/release/libmpv_mpris2.so mpris-x86_64-unknown-linux-gnu.so
      - if: startsWith(github.ref, 'refs/tags/v')
        run: strip --strip-unneeded mpris-x86_64-unknown-linux-gnu.so
      - if: startsWith(github.ref, 'refs/tags/v')
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: mpris-x86_64-unknown-linux-gnu.so
      - name: Install required clippy tools
        run: cargo install clippy-sarif sarif-fmt
        continue-on-error: true
      - name: Run rust-clippy
        run: cargo clippy --all-features --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true
